apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t8tk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t8tk
    app.kubernetes.io/part-of: tkrw-pr712-0075-0058-app
  name: devfile-sample-t8tk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t8tk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t8tk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0058-tenant/tkrw-pr712-0075-0058-app/devfile-sample-t8tk@sha256:46c5457162c03161f1b2f4059fb32ecd6218f75331d5b7725dd85eb5114f0959
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
